<a href="https://colab.research.google.com/github/Satya1247/apssdc_ece/blob/master/boston.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# boston housing price prediction
import numpy as np
import pandas as pd
import sklearn
import matplotlib.pyplot as plt


In [ ]:
# dataset
from sklearn.datasets import load_boston

In [ ]:
# load data
boston=load_boston()
boston

{'DESCR': ".. _boston_dataset:\n\nBoston house prices dataset\n---------------------------\n\n**Data Set Characteristics:**  \n\n    :Number of Instances: 506 \n\n    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.\n\n    :Attribute Information (in order):\n        - CRIM     per capita crime rate by town\n        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.\n        - INDUS    proportion of non-retail business acres per town\n        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\n        - NOX      nitric oxides concentration (parts per 10 million)\n        - RM       average number of rooms per dwelling\n        - AGE      proportion of owner-occupied units built prior to 1940\n        - DIS      weighted distances to five Boston employment centres\n        - RAD      index of accessibility to radial highways\n        - TAX      full-value property-tax rate p

In [ ]:
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [ ]:
boston['DESCR']

".. _boston_dataset:\n\nBoston house prices dataset\n---------------------------\n\n**Data Set Characteristics:**  \n\n    :Number of Instances: 506 \n\n    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.\n\n    :Attribute Information (in order):\n        - CRIM     per capita crime rate by town\n        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.\n        - INDUS    proportion of non-retail business acres per town\n        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\n        - NOX      nitric oxides concentration (parts per 10 million)\n        - RM       average number of rooms per dwelling\n        - AGE      proportion of owner-occupied units built prior to 1940\n        - DIS      weighted distances to five Boston employment centres\n        - RAD      index of accessibility to radial highways\n        - TAX      full-value property-tax rate per $10,000

In [ ]:
boston.data.shape  #boston['data']

(506, 13)

In [ ]:
bos=pd.DataFrame(boston.data)
print(bos.head(3))
print(bos.columns)

        0     1     2    3      4   ...   8      9     10      11    12
0  0.00632  18.0  2.31  0.0  0.538  ...  1.0  296.0  15.3  396.90  4.98
1  0.02731   0.0  7.07  0.0  0.469  ...  2.0  242.0  17.8  396.90  9.14
2  0.02729   0.0  7.07  0.0  0.469  ...  2.0  242.0  17.8  392.83  4.03

[3 rows x 13 columns]
RangeIndex(start=0, stop=13, step=1)


In [ ]:
print(boston.feature_names)
bos.columns=boston.feature_names
print(bos.head(5))

['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']
      CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
0  0.00632  18.0   2.31   0.0  0.538  ...  1.0  296.0     15.3  396.90   4.98
1  0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
2  0.02729   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  392.83   4.03
3  0.03237   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.63   2.94
4  0.06905   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  396.90   5.33

[5 rows x 13 columns]


In [ ]:
bos['PRICE']=boston.target
print(bos.head(3))

      CRIM    ZN  INDUS  CHAS    NOX  ...    TAX  PTRATIO       B  LSTAT  PRICE
0  0.00632  18.0   2.31   0.0  0.538  ...  296.0     15.3  396.90   4.98   24.0
1  0.02731   0.0   7.07   0.0  0.469  ...  242.0     17.8  396.90   9.14   21.6
2  0.02729   0.0   7.07   0.0  0.469  ...  242.0     17.8  392.83   4.03   34.7

[3 rows x 14 columns]


In [ ]:
bos.shape

(506, 14)

In [ ]:
Y=bos['PRICE']   # dependent variable
x=bos.drop('PRICE',axis=1)  # independent variable
print(x.head())
print(Y.head())

      CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
0  0.00632  18.0   2.31   0.0  0.538  ...  1.0  296.0     15.3  396.90   4.98
1  0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
2  0.02729   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  392.83   4.03
3  0.03237   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.63   2.94
4  0.06905   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  396.90   5.33

[5 rows x 13 columns]
0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
Name: PRICE, dtype: float64


In [ ]:
# split train and test data
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=sklearn.model_selection.train_test_split(x,Y,test_size=0.33,random_state=0)

In [ ]:
from sklearn.linear_model import LinearRegression
mymodel=LinearRegression()
mymodel.fit(X_train,Y_train)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
Y_train_pred=mymodel.predict(X_train)
Y_test_pred=mymodel.predict(X_test)

In [ ]:
df=pd.DataFrame(Y_test_pred,Y_test)
print(df.head())

               0
PRICE           
22.6   25.057244
50.0   24.054080
23.0   29.259381
8.3    12.057501
21.2   21.185812


In [ ]:
# mean square error
from sklearn.metrics import mean_squared_error
mse=mean_squared_error(Y_test,Y_test_pred)
mse

26.558581842040695

In [ ]:
mymodel.coef_ ## there are 13 variables so 13 coeffients

array([-1.19139697e-01,  4.76307169e-02,  3.11385581e-03,  2.51765094e+00,
       -1.65965017e+01,  3.66544866e+00, -1.13971582e-02, -1.58813261e+00,
        2.52228398e-01, -1.08619777e-02, -1.04804097e+00,  6.18082895e-03,
       -5.19802805e-01])

In [ ]:
mymodel.intercept_

40.82365137166755

In [ ]:
X_test.head(1).values  # array

array([[6.7240e-02, 0.0000e+00, 3.2400e+00, 0.0000e+00, 4.6000e-01,
        6.3330e+00, 1.7200e+01, 5.2146e+00, 4.0000e+00, 4.3000e+02,
        1.6900e+01, 3.7521e+02, 7.3400e+00]])

In [ ]:
mymodel.predict([[6.7240e-02, 0.0000e+00, 3.2400e+00, 0.0000e+00, 4.6000e-01,
        6.3330e+00, 1.7200e+01, 5.2146e+00, 4.0000e+00, 4.3000e+02,
        1.6900e+01, 3.7521e+02, 7.3400e+00]])

array([25.05724449])

In [ ]:
# save the model to disk
import joblib

In [ ]:
file='pricemodel.sav'

In [ ]:
joblib.dump(mymodel,file)

['pricemodel.sav']

In [ ]:
#load a model from disk
loaded_model=joblib.load(file)
loaded_model.predict([[6.7240e-02, 0.0000e+00, 3.2400e+00, 0.0000e+00, 4.6000e-01,
        6.3330e+00, 1.7200e+01, 5.2146e+00, 4.0000e+00, 4.3000e+02,
        1.6900e+01, 3.7521e+02, 7.3400e+00]])

array([25.05724449])

In [ ]:
df=pd.read_csv("recruit1.csv")
df

experience  test  interview  salary
0        NaN   8.0          9   50000
1        two  10.0         10   65000
2        NaN   8.0          6   45000
3       five   6.0          7   60000
4      seven   9.0          6   70000
5     eleven   9.0          8   80000
6        ten   NaN          7   72000
7      three   7.0         10   62000

In [ ]:
df['experience']=df['experience'].fillna("zeros")
df

experience  test  interview  salary
0       zero   8.0          9   50000
1        two  10.0         10   65000
2       zero   8.0          6   45000
3       five   6.0          7   60000
4      seven   9.0          6   70000
5     eleven   9.0          8   80000
6        ten   NaN          7   72000
7      three   7.0         10   62000

In [ ]:
df['test']=df['test'].fillna(0)

In [ ]:
df

experience  test  interview  salary
0       zero   8.0          9   50000
1        two  10.0         10   65000
2       zero   8.0          6   45000
3       five   6.0          7   60000
4      seven   9.0          6   70000
5     eleven   9.0          8   80000
6        ten   0.0          7   72000
7      three   7.0         10   62000

In [ ]:
!pip install word2number

  Created wheel for word2number: filename=word2number-1.1-cp37-none-any.whl size=5584 sha256=5426d5f393118f5d6b9798c966d812e7e626b49744263c88050836754784d5ce
  Stored in directory: /root/.cache/pip/wheels/46/2f/53/5f5c1d275492f2fce1cdab9a9bb12d49286dead829a4078e0e
Successfully built word2number


In [ ]:
from word2number import w2n

In [ ]:
df['experience']=df['experience'].apply(w2n.word_to_num)

In [ ]:
df

experience  test  interview  salary
0           0   8.0          9   50000
1           2  10.0         10   65000
2           0   8.0          6   45000
3           5   6.0          7   60000
4           7   9.0          6   70000
5          11   9.0          8   80000
6          10   0.0          7   72000
7           3   7.0         10   62000